name = "MehremLonderganMacfarlaneFactors"
uuid = "9c8a161c-d3f7-420d-8d49-ed91ce02d8d6"
authors = ["Henry Gebhardt <hsggebhardt@fastmail.com> and contributors"]
version = "0.0.1"

[deps]
Jacobi = "83f21c0b-4282-5fbc-9e3f-f6da3d2e584c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"

[compat]
Jacobi = "0.7.0"
SpecialFunctions = "2.4.0"
WignerSymbols = "2.0.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
